name: Live Log Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - shell: pwsh
        run: |
          1..30 | ForEach-Object {
            Write-Host "Tick $_ $(Get-Date)"
            Start-Sleep 2
          }
